from typing import Protocol

from money_graph.application.dto.active_analysis import AnalysisSnapshot


class ActiveAnalysisStore(Protocol):
    def get(self) -> AnalysisSnapshot | None: ...
    def replace(self, snapshot: AnalysisSnapshot) -> None: ...
    def try_start_analysis(self) -> bool: ...
    def finish_analysis(self) -> None: ...
